[versions]
spock = "2.0-groovy-3.0"

[libraries]
asciidoctorj = "org.asciidoctor:asciidoctorj:1.5.8.1"
commons-io = "commons-io:commons-io:2.11.0"
commons-lang3 = "org.apache.commons:commons-lang3:3.12.0"
groovy = "org.codehaus.groovy:groovy:3.0.8"
junit = "junit:junit:4.13.2"
junit-vintage-engine = "org.junit.vintage:junit-vintage-engine:5.8.1"
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
objenesis = "org.objenesis:objenesis:3.2"
spock-core = { module="org.spockframework:spock-core", version.ref="spock" }
spock-junit4 = { module="org.spockframework:spock-junit4", version.ref="spock" }
typesafe-config = "com.typesafe:config:1.4.1"

[bundles]
spock = ["spock-core", "spock-junit4"]